---
codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: "diff,files,footer"
  require_changes: false
coverage:
  precision: 2
  range: "80...100"
  round: down
  status:
    project:
      default:
        informational: true
    patch: false
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
