---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:

  pre-commit:
    uses: broadinstitute/shared-workflows/.github/workflows/pre-commit.yaml@v2.0.0
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/python-lint.yaml@tex_rel
  unit-tests:
    uses: broadinstitute/shared-workflows/.github/workflows/python-unit-test.yaml@tex_rel
    with:
      python_package_name: pysudoers
