---
name: "checks"
permissions:
  contents: read
  pull-requests: read

"on":
  pull_request:
    branches:
      - "main"

jobs:
  conventional-commits:
    permissions:
      contents: read
      pull-requests: write
    uses: broadinstitute/shared-workflows/.github/workflows/conventional-commit.yaml@v5.0.0
  pre-commit:
    uses: broadinstitute/shared-workflows/.github/workflows/pre-commit.yaml@v5.0.0
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/python-lint.yaml@v5.0.0
    with:
      ruff_version: '0.8.6'
      use_pylama: false
      use_ruff: true
  unit-tests:
    uses: broadinstitute/shared-workflows/.github/workflows/python-unit-test.yaml@v5.0.0
    with:
      python_package_name: pysudoers
      run_coverage: false
      test_runner: pytest
