---
name: 'test_deploy'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  pypi_test_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/python-test-deploy-to-pypi.yaml@tex_rel
    secrets:
      pypi_test_token: ${{ secrets.PYPI_TEST_TOKEN }}
